#pragma once
// Auto from metadata pack — display names only
namespace giti {
struct Identity { int id; const char* title; const char* branch; const char* color; const char* mood; const char* voice; const char* power; };
inline constexpr Identity kIdentities[50] = {
  {1, "The First Breath", "Breath", "Cyan", "origin", "A single human breath across a reed", "Clears every stray noise from a space until one clean tone remains"},
  {2, "Santur Rain", "Strings", "Violet", "bright", "Metal hammer-lines that fall like light rain", "Brightens a room without raising volume"},
  {3, "Cradle Song", "Voice", "Magenta", "sleep", "A voice that never quite becomes words", "Settles the body into rest"},
  {4, "Daf Heart", "Pulse", "Red", "steady", "Frame-drum pulse under the ribs", "Keeps time for a crowd that must not scatter"},
  {5, "Spring Bell", "Earth & Water", "Emerald", "clear", "Water on glass and distant metal", "Marks a clean beginning"},
  {6, "Ney Dawn", "Breath", "Cyan", "first light", "Ney air at the edge of night", "Opens the day without a shout"},
  {7, "Tar Oath", "Strings", "Violet", "trust", "Long-string vow of the tar", "Binds a promise into the air"},
  {8, "Throat Star", "Voice", "Magenta", "overtone", "Overtone that sits above the spoken line", "Lifts a single note into a constellation"},
  {9, "Tombak Rain", "Pulse", "Red", "patter", "Finger-rain on goblet drum", "Turns scattered steps into one path"},
  {10, "Cave Choir", "Earth & Water", "Emerald", "hollow", "Stone-hollow resonance", "Gives depth to what would stay flat"},
  {11, "Glass Whisper", "Breath", "Cyan", "hush", "Breath against thin glass", "Quiets a room to a single edge"},
  {12, "Setar Thread", "Strings", "Violet", "tender", "Three-string thread of setar", "Draws a fine line through noise"},
  {13, "Mother Tongue", "Voice", "Magenta", "home", "First language before words", "Returns the listener to home"},
  {14, "Walk, Not March", "Pulse", "Red", "gentle", "Soft footfall pulse", "Moves a crowd without force"},
  {15, "River Glass", "Earth & Water", "Emerald", "flow", "River light on glass", "Keeps motion without hurry"},
  {16, "Kite Wind", "Breath", "Cyan", "open sky", "Wind through a taut string", "Opens space above the head"},
  {17, "Kamancheh Tide", "Strings", "Violet", "grief", "Bowed tide of kamancheh", "Carries grief without drowning"},
  {18, "Choir of Salt", "Voice", "Magenta", "harbor", "Many voices at the harbor edge", "Holds a gathering in one chord"},
  {19, "Zarb Ember", "Pulse", "Red", "kindling", "Ember strikes on zarb", "Kindles focus from scattered heat"},
  {20, "Rain Loom", "Earth & Water", "Emerald", "soak", "Rain woven through leaves", "Soaks tension out of the air"},
  {21, "Frost Reed", "Breath", "Cyan", "stillness", "Reed in cold air", "Holds stillness without freeze"},
  {22, "Oud Ember", "Strings", "Violet", "dusk", "Oud body at dusk", "Warms the last light"},
  {23, "Ghazal Bloom", "Voice", "Magenta", "longing", "Sung couplet that opens", "Lets longing bloom without breaking"},
  {24, "Anvil Psalm", "Pulse", "Red", "forge", "Hammer-psalm on iron", "Forges will from repetition"},
  {25, "Forest Throat", "Earth & Water", "Emerald", "green", "Wood, birdsong and bark resonances", "Living texture that reminds people they belong here"},
  {26, "Monsoon Sigh", "Breath", "Cyan", "release", "Long release of wet air", "Releases held pressure"},
  {27, "Barbat Lantern", "Strings", "Violet", "guiding", "Barbat as a hanging lantern", "Guides without pointing"},
  {28, "Call at Dusk", "Voice", "Magenta", "gathering", "Call that gathers at dusk", "Brings the scattered home"},
  {29, "Stone Drum", "Pulse", "Red", "ancient", "Drum under stone", "Anchors time to the old beat"},
  {30, "Salt Desert Hum", "Earth & Water", "Emerald", "vast", "Hum across salt flats", "Makes vastness bearable"},
  {31, "Cloud Choir", "Breath", "Cyan", "shimmer", "Breath in high cloud", "Shimmers without glare"},
  {32, "Qanun Loom", "Strings", "Violet", "weaving", "Qanun as a loom of light", "Weaves many lines into one cloth"},
  {33, "Laughter Loom", "Voice", "Magenta", "warmth", "Laughter that becomes tone", "Warms a cold room"},
  {34, "Heartbeat Chorus", "Pulse", "Red", "kin", "Many hearts as one pulse", "Knits kin into rhythm"},
  {35, "Tide Ledger", "Earth & Water", "Emerald", "memory", "Tide that writes and erases", "Keeps memory without weight"},
  {36, "Silent Horn", "Breath", "Cyan", "pause", "Horn held just before sound", "Protects the pause"},
  {37, "Chang Cathedral", "Strings", "Violet", "vaulted", "Chang under a vault", "Raises the ceiling of the room"},
  {38, "Hum of Forgiveness", "Voice", "Magenta", "soft", "Soft hum after conflict", "Softens the edge of blame"},
  {39, "Sub Vow", "Pulse", "Red", "depth", "Vow under the floor", "Holds depth without collapse"},
  {40, "Seed Chime", "Earth & Water", "Emerald", "promise", "Chime of a seed in soil", "Promises growth without rush"},
  {41, "Sky Lung", "Breath", "Cyan", "unison", "One lung of the sky", "Breathes the room into unison"},
  {42, "Rubab Storm", "Strings", "Violet", "surge", "Rubab in a sudden surge", "Surges and settles clean"},
  {43, "Ten Thousand Voices", "Voice", "Magenta", "many", "Crowd that becomes one voice", "Holds many without chaos"},
  {44, "Thunder Lullaby", "Pulse", "Red", "storm calm", "Thunder turned to lullaby", "Calms after the storm"},
  {45, "Root Drone", "Earth & Water", "Emerald", "grounded", "Drone of roots underfoot", "Grounds the standing body"},
  {46, "Last Horizon", "Breath", "Cyan", "distance", "Breath at the far line", "Keeps distance without loss"},
  {47, "Nine Thousand Strings", "Strings", "Violet", "constellation", "Strings as a night field", "Maps a constellation of touch"},
  {48, "The Sung Name", "Voice", "Magenta", "recognition", "Name sung until known", "Returns recognition"},
  {49, "Pulse of Succession", "Pulse", "Red", "handover", "Pulse that hands the beat forward", "Passes the count without break"},
  {50, "The Last Voice", "Earth & Water", "Emerald", "succession", "The unison of all forty-nine before it", "One chord made of every GITI voice, handing the world to KAYHAN"},
};
} // namespace giti
