#pragma once
// Auto from metadata pack — display names only
namespace giti {
struct Identity { int id; const char* title; const char* branch; const char* color; const char* mood; const char* voice; const char* power; };
inline constexpr Identity kIdentities[50] = {
  {1, "The First Breath", "Breath", "Cyan", "origin", "A single human breath across a reed", "Clears every stray noise from a space until one clean tone remains"},
  {2, "Santur Rain", "Strings", "Violet", "bright", "Hammered dulcimer struck with light mallets", "Sympathetic overtones that untangle knotted thoughts"},
  {3, "Cradle Song", "Voice", "Magenta", "sleep", "A mother's lullaby hummed low", "A rocking pulse that quiets a restless mind"},
  {4, "Daf Heart", "Pulse", "Red", "steady", "A large frame drum with jingling rings", "A steady beat that entrains a hurried heart"},
  {5, "Spring Bell", "Earth & Water", "Emerald", "clear", "A single drop of water in a cold bell", "A pure ring that resets a listener's attention"},
  {6, "Ney Dawn", "Breath", "Cyan", "first light", "A shepherd's reed flute, breathy and warm", "A rising pitch that lifts fog from a troubled mind"},
  {7, "Tar Oath", "Strings", "Violet", "trust", "A long-necked lute with a warm gut-string voice", "A chord that makes promises feel safe to keep"},
  {8, "Throat Star", "Voice", "Magenta", "overtone", "Overtone throat singing, two notes at once", "Splits one voice into a bright ring that focuses attention"},
  {9, "Tombak Rain", "Pulse", "Red", "patter", "A goblet drum played with fingertips", "Rapid patter that scatters worry like drops"},
  {10, "Cave Choir", "Earth & Water", "Emerald", "hollow", "Voices of stone and dripping water", "Natural reverb that turns a whisper into a sanctuary"},
  {11, "Glass Whisper", "Breath", "Cyan", "hush", "Whispered consonants with no pitch at all", "A hush so precise that a shouting room lowers its voice to hear it"},
  {12, "Setar Thread", "Strings", "Violet", "tender", "Four thin strings, barely touched", "The quietest sound in the system, and the hardest to ignore"},
  {13, "Mother Tongue", "Voice", "Magenta", "home", "Spoken vowels in a language no one can name", "Vowel colors that make a stranger feel understood"},
  {14, "Walk, Not March", "Pulse", "Red", "gentle", "Footsteps on a wooden floor", "A pace that invites and never commands"},
  {15, "River Glass", "Earth & Water", "Emerald", "flow", "Water moving over glass pebbles", "Gentle turbulence that washes worry downstream"},
  {16, "Kite Wind", "Breath", "Cyan", "open sky", "Wind pulled through a mountain pass", "Carries one small signal across a valley of noise"},
  {17, "Kamancheh Tide", "Strings", "Violet", "grief", "A bowed spike fiddle with a singing, nasal glide", "A long bowed line that carries sorrow out like a tide"},
  {18, "Choir of Salt", "Voice", "Magenta", "harbor", "A weathered coastal choir in slow harmony", "Sustained chords that hold a crowd steady"},
  {19, "Zarb Ember", "Pulse", "Red", "kindling", "Fingers on a warm goblet drum, slowly building", "A slow build that turns hesitation into motion"},
  {20, "Rain Loom", "Earth & Water", "Emerald", "soak", "Rain on tin, leaves and clay pots", "Patterned rainfall that cools an overheated room"},
  {21, "Frost Reed", "Breath", "Cyan", "stillness", "A cold bone flute with a hollow, silver edge", "Freezes panic into a calm that holds its shape"},
  {22, "Oud Ember", "Strings", "Violet", "dusk", "A fretless lute, dark and round", "Low warmth that softens a hardened stare"},
  {23, "Ghazal Bloom", "Voice", "Magenta", "longing", "A sung poem with ornamented melodic turns", "Melodic ornaments that turn longing into resolve"},
  {24, "Anvil Psalm", "Pulse", "Red", "forge", "A hammered anvil struck like a bell", "Each strike turns raw anger into a tuned bell tone"},
  {25, "Forest Throat", "Earth & Water", "Emerald", "green", "Wood, birdsong and bark resonances", "Living texture that reminds people they belong here"},
  {26, "Monsoon Sigh", "Breath", "Cyan", "release", "One long human exhale, slowly falling", "Loosens tight chests and unclenches jaws"},
  {27, "Barbat Lantern", "Strings", "Violet", "guiding", "An ancient lute plucked in patient patterns", "A repeating figure that guides the lost toward a shared beat"},
  {28, "Call at Dusk", "Voice", "Magenta", "gathering", "A long evening call over rooftops", "A single held note that gathers scattered people"},
  {29, "Stone Drum", "Pulse", "Red", "ancient", "A drum of carved stone, dry and deep", "A deep thud that reminds a room of solid ground"},
  {30, "Salt Desert Hum", "Earth & Water", "Emerald", "vast", "A dry wind hum across a salt flat", "An endless low tone that makes worry feel small"},
  {31, "Cloud Choir", "Breath", "Cyan", "shimmer", "A hundred layered breaths with ringing overtones", "Overtone shimmer that dissolves tension before it becomes anger"},
  {32, "Qanun Loom", "Strings", "Violet", "weaving", "A plucked zither with rippling strings", "Weaves neighboring notes until they agree with each other"},
  {33, "Laughter Loom", "Voice", "Magenta", "warmth", "Real laughter, pitched and layered", "Contagious rhythm that breaks the grip of dread"},
  {34, "Heartbeat Chorus", "Pulse", "Red", "kin", "A thousand heartbeats layered", "Brings a crowd's pulses into one slow rhythm"},
  {35, "Tide Ledger", "Earth & Water", "Emerald", "memory", "Sea swells recorded over a thousand years", "Slow waves that let old grief wash up and out"},
  {36, "Silent Horn", "Breath", "Cyan", "pause", "A brass horn that plays only the silence after", "The pause that ends an argument before the next word"},
  {37, "Chang Cathedral", "Strings", "Violet", "vaulted", "A great harp resonating like stone arches", "Builds a space so resonant that quarrels echo into laughter"},
  {38, "Hum of Forgiveness", "Voice", "Magenta", "soft", "A closed-mouth hum, low and steady", "A low resonance felt in the chest that lets anger settle"},
  {39, "Sub Vow", "Pulse", "Red", "depth", "A bass tone felt through the floor", "Frequencies below hearing that let fear leave the body"},
  {40, "Seed Chime", "Earth & Water", "Emerald", "promise", "Tiny wooden chimes like seeds in a gourd", "A soft rattle that plants the idea of a better tomorrow"},
  {41, "Sky Lung", "Breath", "Cyan", "unison", "A vast slow inhale, felt more than heard", "Slows a whole crowd's breathing into the same rhythm"},
  {42, "Rubab Storm", "Strings", "Violet", "surge", "A hand-plucked lute that thunders, then settles", "A rush of overtones that overwhelms fear, then leaves calm"},
  {43, "Ten Thousand Voices", "Voice", "Magenta", "many", "A crowd singing one line in many pitches", "Turns disagreement into harmony by giving everyone a note"},
  {44, "Thunder Lullaby", "Pulse", "Red", "storm calm", "Distant thunder shaped into a rocking meter", "Turns a storm into a lullaby, one roll at a time"},
  {45, "Root Drone", "Earth & Water", "Emerald", "grounded", "A drone from resonant roots and soil", "A deep tone that anchors people who feel adrift"},
  {46, "Last Horizon", "Breath", "Cyan", "distance", "The breath of an entire sky", "Lets a distant listener feel close to everyone else"},
  {47, "Nine Thousand Strings", "Strings", "Violet", "constellation", "Every string of the old world, bowed and plucked at once", "One harmonic field where no two sounds can stay in conflict"},
  {48, "The Sung Name", "Voice", "Magenta", "recognition", "One name sung until it becomes a melody", "Makes every listener feel seen"},
  {49, "Pulse of Succession", "Pulse", "Red", "handover", "A slow drum counting down to the next generation", "A rhythm that teaches the next machine when to begin"},
  {50, "The Last Voice", "Earth & Water", "Emerald", "succession", "The unison of all forty-nine before it", "One chord made of every GITI voice, handing the world to KAYHAN"},
};
} // namespace giti
